---
  language: ruby
  script: bundle exec middleman build
  env:
    global:
      - GIT_COMMITER_NAME=hiroraba
      - GIT_COMMITER_EMAIL=hiroraba@gmail.com
      - GIT_AUTHOR_NAME=hiroraba
      - GIT_AUTHOR_EMAIL=hiroraba@gmail.com
      - secure: "H1JT75+HjWh/zi98qe9O2D565O5rmaPyAZmZ0dfMIPbzEaEJvKlaVyUs8SgLNule/xT4ij5fDJMij87ogrYspOGWx5KCLVwxD07zZStm2iqM8k5VIFVOR5nxz+too9R5Tu96rUVcF5pOd9+dF8fiXfKZ5RrbAaZKNZ9oj/QYiyk="
    before_script:
      - git clone --quiet https://github.com/hiroraba/hiroraba.git build
      - pushd build
      - git checkout -b gh-pages
      - popd
    after_success:
      - cd build
      - git add -A
      - git commit -m 'Update'
      - - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/hiroraba.git gh-pages 2> /dev/null'
